name: Freeze
main: NawafPluginFrz\Nawaf1b
version: 1.0.0
api: 2.0.0
load: POSTWORLD
author: Nawaf1b
commands:
  freeze:
    usage: "/freeze <add/remove>"
permissions:
  freeze.command:
    default: op

